<?php

// Load Nette Framework or autoloader generated by Composer
require __DIR__ . '/../vendor/autoload.php';


$configurator = new Nette\Configurator;

// Enable Nette Debugger for error visualisation & logging
$configurator->setDebugMode(FALSE);
$configurator->enableDebugger(__DIR__ . '/../log');

// Specify folder for cache
$configurator->setTempDirectory(__DIR__ . '/../temp');

// Enable RobotLoader - this will load all classes automatically
$configurator->createRobotLoader()
	->addDirectory(__DIR__)
	->addDirectory(__DIR__ . '/../vendor/others')
	->addDirectory(__DIR__ . '/../vendor/OrbisRex')
	->register();

// Create Dependency Injection container from config.neon file
$configurator->addConfig(__DIR__ . '/WesprModule/config/config.neon');
$configurator->addConfig(__DIR__ . '/FrontModule/config/config.neon');
$container = $configurator->createContainer();

//Extensions///////////////////////////////////////////////////
//Date input from HTML 5
\Nette\Forms\Container::extensionMethod('addDate', function (\Nette\Forms\Container $form, $name, $label = NULL) {
    $form[$name] = new \Nette\Forms\Controls\TextDate($label);
    return $form[$name];
});

//Time input from HTML 5
\Nette\Forms\Container::extensionMethod('addTime', function (\Nette\Forms\Container $form, $name, $label = NULL) {
    $form[$name] = new \Nette\Forms\Controls\TextTime($label);
    return $form[$name];
});

return $container;
